"""
GoT 推理引擎 (Graph of Thought Engine)
----------------------------------------
NAN-Agent 的核心推理引擎，将 Graph of Thought 推理系统的所有组件
整合为一个可运行的推理循环。

组件架构：
    GoTEngine
    ├── GoTGraph          — 推理图数据结构
    ├── NodePool          — 活跃节点池
    ├── DMNGenerator      — 默认模式网络（空闲时自发思考）
    ├── GoTScheduler      — 批次调度器（并行处理节点）
    ├── ReasoningLoop     — 推理循环（分析→思考→元认知→决策分支）
    ├── MetaCognition     — 元认知（质量验证、矛盾检测）
    ├── GoTToolkit        — 工具集（代码执行、搜索能力）
    ├── DrawOfThought     — 画图思考（可视化推理）
    └── TA 集成           — 与 TaskAgent 的双向通信

生命周期模型：
    引擎以统一的 _lifecycle 循环运行，不再区分"后台模式"和"前台模式"。
    CEN（外部输入）只是另一种输入源，与感知、工具返回、DMN 自发生成
    处于同等地位——无需显式模式切换。

    每个 tick：
    1. 消费外部输入（CEN、感知、工具返回）
    2. 若节点池非空，调度器处理批次
    3. 若节点池为空，DMN 自发生成节点
    4. 扩散激活传播 + 全局衰减
    5. 周期性任务（自动保存、记忆反思）
    6. 等待 tick 间隔

持久化：
    图可通过 save_graph / load_graph 序列化到 JSON 文件，
    并支持自动保存（auto_save_interval）和启停时自动加载/保存。

主要入口：
    engine.start()          — 启动后台推理循环
    engine.run_loop()       — 运行主推理循环（阻塞，向后兼容）
    engine.step()           — 执行单步推理
    engine.create_task_node() — 从外部注入任务节点
    engine.save_graph()     — 保存图到文件
    engine.load_graph()     — 从文件加载图
"""

import asyncio
import hashlib
import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from nan_agent.inference.graph import GoTGraph, GoTNode, GoTEdge, NodeType, EdgeType, NodeOrigin
from nan_agent.inference.node_pool import NodePool
from nan_agent.inference.dmn import (
    DMNGenerator,
    SpontaneousGrowthStrategy,
    GrowthStrategy,
    GenerationMode,
)
from nan_agent.inference.scheduler import GoTScheduler, BatchResult
from nan_agent.inference.reasoning_loop import ReasoningLoop
from nan_agent.inference.metacognition import MetaCognition
from nan_agent.inference.tools import GoTToolkit
from nan_agent.inference.draw_of_thought import DrawOfThought
from nan_agent.logging.logger import get_logger, Timer, log_event

logger = get_logger(__name__)


@dataclass
class EngineStats:
    """Engine statistics snapshot.

    Attributes:
        total_nodes: Total number of nodes in the graph.
        active_nodes: Number of active (non-pruned) nodes.
        total_edges: Total number of edges in the graph.
        pool_size: Number of nodes in the active pool.
        action_queue_size: Number of pending actions.
        steps_run: Total steps executed.
        nodes_processed: Total nodes processed by the scheduler.
        pruned_nodes: Total nodes pruned.
        dmn_generated: Total nodes generated by DMN.
        uptime_seconds: Engine uptime in seconds.
        graph_entropy: Structural entropy of the graph (0.0-1.0).
        total_activations: Sum of all node activation energies.
        growth_strategy: Name of the current DMN growth strategy.
    """
    total_nodes: int = 0
    active_nodes: int = 0
    total_edges: int = 0
    pool_size: int = 0
    action_queue_size: int = 0
    steps_run: int = 0
    nodes_processed: int = 0
    pruned_nodes: int = 0
    dmn_generated: int = 0
    uptime_seconds: float = 0.0
    # ── 新增字段 ──
    graph_entropy: float = 0.0       # 图的结构熵
    total_activations: float = 0.0   # 所有节点激活能量总和
    growth_strategy: str = ""        # 当前 DMN 增长策略名称


class GoTEngine:
    """Graph of Thought 推理引擎

    NAN-Agent 的核心推理组件，整合图推理、记忆、元认知、工具调用和
    画图思考等能力，构成一个持续运行的自主推理循环。

    生命周期模型：
    引擎以统一的 _lifecycle 循环运行，CEN 只是另一种输入源，
    无需显式模式切换。每个 tick：
    1. 消费外部输入（CEN、感知、工具返回）
    2. 若节点池非空，调度器处理批次
    3. 若节点池为空，DMN 自发生成节点
    4. 扩散激活传播 + 全局衰减
    5. 周期性任务（自动保存、记忆反思）
    6. 等待 tick 间隔

    持久化：
    图可通过 save_graph / load_graph 序列化到 JSON 文件，
    并支持自动保存和启停时自动加载/保存。

    TA 集成 (TA ↔ GoT):
    - receive_from_ta(): TA 向 GoT 图注入新节点
    - _dispatch_actions(): GoT 将动作分发到 TA 执行
    - _consume_ta_push(): 消费 TA 的消息队列
    """

    def __init__(
        self,
        cognition,
        hard_memory=None,
        self_value=None,
        soft_memory=None,
        web_search=None,
        code_executor=None,
        config=None,
        task_agent_factory=None,
        embedding_provider=None,
    ):
        self._cognition = cognition
        self._hard_memory = hard_memory
        self._self_value = self_value
        self._soft_memory = soft_memory
        self._config = config or {}

        # ── Tick 间隔配置 ──
        self._tick_interval: float = self._config.get("tick_interval", 1.0)

        # ── 自动保存配置 ──
        self._auto_save_interval: int = self._config.get("auto_save_interval", 50)
        self._graph_save_path: Optional[str] = self._config.get("graph_save_path", None)
        self._steps_since_last_save: int = 0

        # ── 批次大小 ──
        self._batch_size: int = self._config.get("batch_size", 5)

        # ── 核心组件 ──
        self.graph = GoTGraph()
        self.pool = NodePool()
        self.action_queue: list[dict] = []

        self._meta = MetaCognition(cognition=cognition, embedding_provider=embedding_provider)
        self._draw_of_thought = DrawOfThought(cognition=cognition)

        self._tools = GoTToolkit(
            cognition=cognition,
            hard_memory=hard_memory,
            web_search=web_search,
            code_executor=code_executor,
        )

        self._dmn = SpontaneousGrowthStrategy(
            cognition=cognition,
            hard_memory=hard_memory,
            graph=self.graph,
            min_pool_size=self._config.get("dmn_min_pool_size", 3),
            config=self._config.get("dmn_config", {}),
            embed_fn=embedding_provider,
        )

        self._reasoning_loop = ReasoningLoop(
            cognition=cognition,
            graph=self.graph,
            hard_memory=hard_memory,
            tools=self._tools,
            meta=self._meta,
            action_queue=self.action_queue,
            draw_of_thought=self._draw_of_thought,
            self_value=self_value,
            soft_memory=soft_memory,
            embed_fn=embedding_provider,
        )

        self._scheduler = GoTScheduler(
            cognition=cognition,
            graph=self.graph,
            pool=self.pool,
            reasoning_loop=self._reasoning_loop,
        )



        # ── 运行状态 ──
        self._running = False
        self._start_time = 0.0
        self._steps_run = 0
        self._nodes_processed = 0
        self._dmn_generated = 0
        self._pruned_nodes = 0
        self._event_bus = None
        self._perception = None



        # ── TA 集成 ──
        self._task_agent_factory = task_agent_factory
        self._pending_tasks: dict[str, asyncio.Task] = {}
        self._ta_push_queue: list[dict] = []  # TA → GoT 的消息队列

        # ── 后台任务引用 ──
        self._lifecycle_task: Optional[asyncio.Task] = None

    # ═══════════════════════════════════════════════════════════
    # 图持久化 (Graph Persistence)
    # ═══════════════════════════════════════════════════════════

    def save_graph(self, path: str) -> None:
        """Serialize the graph to a JSON file.

        Args:
            path: Absolute or relative file path for the JSON output.
        """
        try:
            data = self.graph.to_dict()
            # 确保目录存在
            Path(path).parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            log_event(logger, "got_graph_saved", path=path, nodes=self.graph.node_count)
        except Exception as e:
            logger.error("got_graph_save_failed", path=path, error=str(e))

    def load_graph(self, path: str) -> None:
        """Load the graph from a JSON file.

        Replaces the current graph and re-populates the node pool
        with all active (non-pruned) nodes from the loaded graph.

        Args:
            path: Absolute or relative file path for the JSON input.
        """
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            self.graph = GoTGraph.from_dict(data)
            # 重建节点池：将所有活跃节点加入池中
            self.pool = NodePool()
            for node in self.graph.get_active_nodes():
                self.pool.add(node)
            # 重新绑定 DMN 的图引用
            self._dmn._graph = self.graph
            # 重新绑定推理循环和调度器的图引用
            self._reasoning_loop._graph = self.graph
            self._scheduler._graph = self.graph
            log_event(
                logger, "got_graph_loaded",
                path=path, nodes=self.graph.node_count,
                active=self.graph.active_count,
            )
        except FileNotFoundError:
            logger.warning("got_graph_load_not_found", path=path)
        except Exception as e:
            logger.error("got_graph_load_failed", path=path, error=str(e))

    # ═══════════════════════════════════════════════════════════
    # 设置器
    # ═══════════════════════════════════════════════════════════

    def set_event_bus(self, event_bus):
        self._event_bus = event_bus

    def set_perception(self, perception):
        self._perception = perception

    @property
    def draw_of_thought(self):
        return self._draw_of_thought

    # ═══════════════════════════════════════════════════════════
    # TA ↔ GoT 双向集成
    # ═══════════════════════════════════════════════════════════

    def receive_from_ta(self, content: str, node_type=None,
                        confidence: float = 0.7) -> str:
        """TA calls this to inject a new node into the GoT graph (TA → GoT).

        The injected node is marked with NodeOrigin.EXTERNAL and receives
        an activation energy injection to ensure it gets processed promptly.

        Returns:
            The node_id of the newly created node.
        """
        # 解析节点类型
        if node_type is None or isinstance(node_type, str):
            try:
                node_type = NodeType(node_type)
            except (ValueError, TypeError) as e:
                logger.debug("got_node_type_fallback", raw=node_type, error=str(e))
                node_type = NodeType.INFERENCE

        # 创建外部来源节点并注入激活能量
        node = GoTNode(
            type=node_type,
            content=content,
            confidence=confidence,
            origin=NodeOrigin.EXTERNAL,  # 标记为外部注入
            metadata={"source": "ta_push"},
        )
        node.inject_activation(5.0)  # 外部输入注入高激活能量

        self.graph.add_node(node)
        self.pool.add(node)
        log_event(
            logger, "got_received_from_ta",
            node_id=node.node_id, type=node_type.name,
        )
        return node.node_id

    async def _consume_ta_push(self):
        """消费 TA 的消息队列并注入图"""
        if not self._ta_push_queue:
            return
        items = list(self._ta_push_queue)
        self._ta_push_queue.clear()
        for item in items:
            self.receive_from_ta(
                content=item.get("content", ""),
                node_type=item.get("node_type", NodeType.INFERENCE),
                confidence=item.get("confidence", 0.7),
            )

    async def _dispatch_actions(self):
        """消费 action_queue。如果 action 标记了 dispatch_to_ta，挂起等待 TA 完成。"""
        if not self.action_queue or not self._task_agent_factory:
            return

        actions = list(self.action_queue)
        self.action_queue.clear()

        for action in actions:
            dispatch_to_ta = action.get("dispatch_to_ta", False)
            task_desc = action.get("task_desc", action.get("content", ""))
            source_node_id = action.get("source_node_id", "")

            if dispatch_to_ta and task_desc:
                # 创建 TA 并异步执行
                task = asyncio.create_task(
                    self._run_ta_action(task_desc, source_node_id)
                )
                self._pending_tasks[source_node_id or hashlib.md5(task_desc.encode()).hexdigest()[:16]] = task
            elif task_desc:
                # 没有 TA，仍然把 action 记录为节点
                node = GoTNode(
                    type=NodeType.ACTION_OUTPUT,
                    content=task_desc,
                    confidence=0.8,
                    origin=NodeOrigin.TOOL_RETURN,  # 工具返回来源
                    metadata={"source": "action_queue"},
                )
                self.graph.add_node(node)
                self.pool.add(node)

    async def _run_ta_action(self, task_desc: str, source_node_id: str):
        """创建 TA 实例执行任务，完成后将结果写回 GoT 图"""
        with Timer(logger, "got_ta_action", warn_threshold_ms=30000):
            logger.info("got_dispatching_to_ta", task=task_desc[:80])
            try:
                ta = self._task_agent_factory()
                result = await ta.run(
                    task=task_desc,
                    source="got_action",
                )
                # TA 结果回写为 GoT 节点
                result_content = result.result if result.result else f"TA done: {task_desc}"
                result_node = GoTNode(
                    type=NodeType.CONCLUSION,
                    content=f"[TA Result] {result_content}",
                    confidence=0.85 if result.success else 0.5,
                    origin=NodeOrigin.TOOL_RETURN,  # 工具返回来源
                    metadata={
                        "source": "ta_result",
                        "source_node_id": source_node_id,
                        "success": result.success,
                        "steps": result.steps_run,
                    },
                )
                result_node.inject_activation(3.0)  # TA 结果注入中等激活能量
                self.graph.add_node(result_node)
                self.pool.add(result_node)
                log_event(logger, "got_ta_result_stored",
                           node_id=result_node.node_id,
                           success=result.success)
            except Exception as e:
                logger.error("got_ta_dispatch_failed", error=str(e))

    async def _periodic_memory_reflection(self):
        """周期性记忆反思"""
        if self._hard_memory:
            await self._hard_memory.recollect("recent experiences and learnings", k=10)

    async def _emit_event(self, event_name: str, **kwargs):
        """发射事件到事件总线"""
        if self._event_bus is not None:
            try:
                await self._event_bus.emit(event_name, **kwargs)
            except Exception as e:
                logger.warning("got_event_emit_failed", event=event_name, error=str(e))

    # ═══════════════════════════════════════════════════════════
    # 外部接口
    # ═══════════════════════════════════════════════════════════

    def create_task_node(self, task: str) -> GoTNode:
        """Create an external task node and inject it into the graph.

        External task nodes are marked with NodeOrigin.EXTERNAL and
        receive a high activation energy injection (5.0) to ensure
        they are processed promptly by the scheduler.

        Args:
            task: The task description text.

        Returns:
            The newly created GoTNode.
        """
        # 创建外部任务节点并注入高激活能量
        node = GoTNode(
            type=NodeType.EXTERNAL_TASK,
            content=task,
            confidence=0.8,
            origin=NodeOrigin.EXTERNAL,  # 标记为外部注入
            metadata={"source": "external_task_injection"},
        )
        node.inject_activation(5.0)  # 外部任务注入高激活能量

        self.graph.add_node(node)
        self.pool.add(node)
        log_event(logger, "got_task_node_created", content=task[:100])
        return node

    async def step(self, batch_size: int = 5) -> EngineStats:
        """Execute a single reasoning step.

        Processes one batch of nodes through the scheduler, and optionally
        generates DMN spontaneous nodes if the pool is below threshold.

        Args:
            batch_size: Maximum number of nodes to process in this step.

        Returns:
            Current engine statistics after the step.
        """
        with Timer(logger, "got_step", warn_threshold_ms=10000):
            self._steps_run += 1

            # DMN 自发节点生成（使用 tick rhythm：轻量/重量交替）
            dmn_task = None
            if self._dmn.should_generate(self.pool.size()):
                dmn_task = asyncio.create_task(self._dmn.tick_async())

            # 调度器处理批次（并行）
            scheduler_task = asyncio.create_task(self._scheduler.process_batch(batch_size=batch_size))

            # 等待 DMN 生成结果
            dmn_added = 0
            if dmn_task is not None:
                with Timer(logger, "dmn_generate", warn_threshold_ms=5000):
                    try:
                        dmn_nodes = await dmn_task
                        for node in dmn_nodes:
                            self.graph.add_node(node)
                            self.pool.add(node)
                            dmn_added += 1
                        self._dmn_generated += dmn_added
                    except Exception:
                        logger.exception("parallel_dmn_generate_failed")

            # 等待调度器结果
            try:
                with Timer(logger, "scheduler_process", warn_threshold_ms=5000):
                    batch_result = await scheduler_task
            except Exception:
                logger.exception("parallel_scheduler_failed")
                batch_result = BatchResult(
                    batch_size=0, new_nodes_count=0,
                    pruned_count=0, action_count=0,
                    errors=["scheduler_failed"], elapsed_ms=0,
                )

            new_count = batch_result.new_nodes_count
            self._nodes_processed += batch_result.batch_size
            self._pruned_nodes += batch_result.pruned_count

            await self._emit_event(
                "got.step_complete",
                steps_run=self._steps_run,
                nodes_processed=self._nodes_processed,
                dmn_generated=dmn_added,
                pool_size=self.pool.size(),
            )

            if self._soft_memory is not None and new_count > 0:
                try:
                    self._soft_memory.track_learning_opportunity(
                        {"new_nodes": new_count, "step": self._steps_run}
                    )
                except Exception as e:
                    logger.warning("got_soft_memory_track_failed", new_nodes=new_count, error=str(e))

            return self.get_stats()

    # ═══════════════════════════════════════════════════════════
    # 统一生命周期循环 (Unified Lifecycle)
    # ═══════════════════════════════════════════════════════════

    async def _consume_inputs(self):
        """消费所有外部输入源（CEN、感知、工具返回）

        将所有外部输入统一为图的节点注入，不再区分模式。
        """
        # 1. 消费 TA 的回推消息（TA → GoT）
        if self._ta_push_queue:
            queue_size = len(self._ta_push_queue)
            await self._consume_ta_push()
            logger.info("cen_consumed", ta_messages=queue_size)

        # 2. 消费 action_queue → 有 TA 的调度过去，没有的继续执行
        if self.action_queue:
            queue_size = len(self.action_queue)
            await self._dispatch_actions()
            logger.info("actions_dispatched", count=queue_size)

        # 3. 持续感知环境
        if self._perception is not None:
            try:
                perception_data = await self._perception.observe()
                if perception_data:
                    # 感知节点标记为外部来源
                    # 将感知数据格式化为可读的自然语言内容
                    sensor_parts = []
                    ts = perception_data.get("timestamp", "")
                    visual = perception_data.get("visual")
                    audio = perception_data.get("audio")
                    speech = perception_data.get("speech")
                    if visual and isinstance(visual, dict):
                        frames = visual.get("frame_count", 0)
                        res = visual.get("resolution", [0, 0])
                        sensor_parts.append(f"Camera: {frames} frames at {res[0]}x{res[1]}")
                    if audio and isinstance(audio, dict):
                        sensor_parts.append(f"Microphone: {audio.get('duration_ms', 0)}ms audio captured")
                    if speech and isinstance(speech, dict):
                        text = speech.get("text", "")
                        if text:
                            sensor_parts.append(f'Speech recognized: "{text}" (confidence: {speech.get("confidence", 0):.2f})')
                    if sensor_parts:
                        perception_text = "[Perception] " + "; ".join(sensor_parts)
                    else:
                        perception_text = f"[Perception] No significant sensor data at {ts}"
                    logger.info("perception_event", sensors=sensor_parts if sensor_parts else ["idle"])
                    perc_node = GoTNode(
                        type=NodeType.DMN_SPONTANEOUS,
                        content=perception_text,
                        confidence=0.8,
                        origin=NodeOrigin.EXTERNAL,  # 感知输入标记为外部
                        metadata={"source": "perception"},
                    )
                    perc_node.inject_activation(3.0)  # 感知输入注入中等激活能量
                    self.graph.add_node(perc_node)
                    self.pool.add(perc_node)
            except Exception as e:
                logger.warning("got_perception_observe_failed", error=str(e))

    async def _periodic_tasks(self):
        """执行周期性任务（自动保存、记忆反思、裁剪等）

        每次调用递增步数计数器，根据配置的间隔执行相应任务。
        """
        self._steps_since_last_save += 1

        # 自动保存图
        if (
            self._auto_save_interval > 0
            and self._graph_save_path is not None
            and self._steps_since_last_save >= self._auto_save_interval
        ):
            try:
                self.save_graph(self._graph_save_path)
                self._steps_since_last_save = 0
            except Exception:
                logger.exception("got_auto_save_failed")

        # 周期性裁剪（每 50 步）
        if self._steps_run % 50 == 0 and hasattr(self, '_reasoning_loop'):
            try:
                self._reasoning_loop.handle_prune()
            except Exception as e:
                logger.warning("got_periodic_prune_failed", error=str(e))

        # 周期性记忆反思
        if self._steps_run % 300 == 0:
            try:
                await self._periodic_memory_reflection()
            except Exception as e:
                logger.warning("got_periodic_memory_reflection_failed", error=str(e))

    async def _lifecycle(self):
        """Unified lifecycle loop — the heartbeat that never stops.

        Replaces the old _got_background_loop and run_loop with a single
        unified loop. CEN is just another input source — no explicit
        mode switching required.

        Each tick:
        1. Consume external inputs (CEN, perception, tool returns)
        2. If pool has nodes, process them via scheduler
        3. If pool is empty, use growth strategy (DMN) to generate spontaneous nodes
        4. Spread activation and decay
        5. Periodic tasks (auto-save, memory reflection)
        6. Tick interval
        """
        self._start_time = time.time()
        log_event(logger, "got_engine_lifecycle_started")
        await self._emit_event("got.engine.started")

        while self._running:
            with Timer(logger, "got_lifecycle_tick", warn_threshold_ms=10000):
                try:
                    # 1. 消费外部输入（CEN、感知、工具返回）
                    await self._consume_inputs()

                    # 2. 若节点池非空，调度器处理批次
                    if not self.pool.is_empty():
                        try:
                            await self._scheduler.process_batch(batch_size=self._batch_size)
                            self._steps_run += 1
                            self._nodes_processed += self._batch_size
                        except Exception:
                            logger.exception("got_scheduler_batch_failed")

                    # 3. 若节点池为空，DMN 自发生成节点（使用 tick rhythm）
                    else:
                        try:
                            new_nodes = await self._dmn.tick_async()
                            for node in new_nodes:
                                self.graph.add_node(node)
                                self.pool.add(node)
                            self._dmn_generated += len(new_nodes)
                            self._steps_run += 1
                            if new_nodes:
                                logger.info(
                                    "dmn_generated",
                                    count=len(new_nodes),
                                    pool_size=self.pool.size(),
                                    total_steps=self._steps_run,
                                )
                        except Exception:
                            logger.exception("got_dmn_grow_failed")

                    # 4. 扩散激活传播 + 全局衰减（仅在 DMN 生成后执行，process_batch 内部已处理）
                    if not self.pool.is_empty():
                        # process_batch 已完成扩散+衰减，跳过
                        pass
                    else:
                        # DMN 刚刚生成了节点，仅执行衰减（扩散由 process_batch 处理）
                        self.graph.decay_all()

                    # 5. 周期性任务（自动保存、记忆反思）
                    await self._periodic_tasks()

                    # 周期性心跳日志（每 50 steps）
                    if self._steps_run % 50 == 0 and self._steps_run > 0:
                        stats = self.get_stats()
                        logger.info(
                            "got_heartbeat",
                            steps=self._steps_run,
                            nodes=stats.total_nodes,
                            active=stats.active_nodes,
                            pool=stats.pool_size,
                            dmn_gen=stats.dmn_generated,
                            entropy=round(stats.graph_entropy, 3),
                        )

                    # 6. 处理 action 输出
                    action_outputs = self.get_action_outputs()
                    for action_node in action_outputs:
                        try:
                            action_desc = (
                                action_node.action_output
                                if hasattr(action_node, 'action_output')
                                else str(action_node)
                            )
                            if self._task_agent_factory:
                                ta = self._task_agent_factory()
                                await ta.run_from_got_action(action_desc)
                        except Exception as e:
                            logger.warning("got_task_agent_run_failed", error=str(e))

                    # 7. 发射步完成事件
                    await self._emit_event(
                        "got.lifecycle.tick_complete",
                        steps_run=self._steps_run,
                        pool_size=self.pool.size(),
                    )

                except Exception:
                    logger.exception("got_lifecycle_tick_failed")

                # 8. 等待 tick 间隔
                await asyncio.sleep(self._tick_interval)

        # 生命周期结束：保存图并发射事件
        if self._graph_save_path is not None:
            try:
                self.save_graph(self._graph_save_path)
            except Exception:
                logger.exception("got_lifecycle_save_on_stop_failed")

        await self._emit_event("got.engine.stopped")
        logger.info("GoT engine lifecycle ended")

    # ═══════════════════════════════════════════════════════════
    # 启停控制
    # ═══════════════════════════════════════════════════════════

    def start(self, perception=None):
        """Start the engine's background lifecycle loop.

        On start, attempts to load an existing graph from the configured
        graph_save_path. Then launches the _lifecycle coroutine as a
        background task.

        Args:
            perception: Optional perception interface for environment sensing.
        """
        if perception is not None:
            self._perception = perception

        # 启动时尝试加载已有图
        if self._graph_save_path is not None:
            try:
                self.load_graph(self._graph_save_path)
            except Exception:
                logger.debug("got_start_load_graph_skipped")

        self._running = True
        self._lifecycle_task = asyncio.ensure_future(self._lifecycle())
        log_event(logger, "got_engine_started")

    async def stop(self):
        """Stop the engine's lifecycle loop gracefully.

        Sets _running to False, which causes the _lifecycle loop to exit
        on its next iteration. The graph is saved on exit if a save path
        is configured.
        """
        self._running = False
        # 等待生命周期任务结束
        if self._lifecycle_task is not None:
            try:
                await asyncio.wait_for(self._lifecycle_task, timeout=self._tick_interval * 2 + 5.0)
            except asyncio.TimeoutError:
                logger.warning("got_lifecycle_stop_timeout")
            except Exception as e:
                logger.warning("got_lifecycle_stop_error", error=str(e))
            self._lifecycle_task = None

        # 停止时保存图
        if self._graph_save_path is not None:
            try:
                self.save_graph(self._graph_save_path)
            except Exception:
                logger.exception("got_stop_save_graph_failed")

        logger.info("GoT engine stop completed")

    async def run_loop(self, batch_size: int = 5, idle_sleep: float = 1.0):
        """Run the main reasoning loop (blocking). Backward-compatible entry point.

        This method now delegates to the unified _lifecycle method.
        The batch_size and idle_sleep parameters are accepted for backward
        compatibility but the actual tick interval is controlled by
        _tick_interval config.

        Args:
            batch_size: Maximum number of nodes to process per batch (backward compat).
            idle_sleep: Sleep interval when idle (backward compat, superseded by _tick_interval).
        """
        # 向后兼容：如果传入了不同的 batch_size，临时覆盖
        if batch_size != self._batch_size:
            self._batch_size = batch_size

        # 确保 _running 为 True，否则 _lifecycle 会立即退出
        if not self._running:
            self._running = True
            self._start_time = time.time()

        await self._lifecycle()

    # ═══════════════════════════════════════════════════════════
    # 统计与查询
    # ═══════════════════════════════════════════════════════════

    def get_stats(self) -> EngineStats:
        """Get current engine statistics.

        Returns:
            An EngineStats snapshot including graph entropy, total
            activations, and current growth strategy name.
        """
        # 计算图的结构熵
        graph_entropy = 0.0
        try:
            graph_entropy = self.graph.structural_entropy()
        except Exception as e:
            logger.warning("got_stats_entropy_failed", error=str(e))

        # 计算所有节点的激活能量总和
        total_activations = 0.0
        try:
            total_activations = sum(n.activation for n in self.graph._nodes.values())
        except Exception as e:
            logger.warning("got_stats_activations_failed", error=str(e))

        # 获取当前 DMN 增长策略名称
        growth_strategy_name = ""
        try:
            # SpontaneousGrowthStrategy 内部维护策略权重，取权重最高的策略
            if hasattr(self._dmn, '_strategy_weights') and self._dmn._strategy_weights:
                best = max(self._dmn._strategy_weights.items(), key=lambda x: x[1])
                growth_strategy_name = best[0].value
        except Exception as e:
            logger.debug("got_stats_strategy_name_failed", error=str(e))

        return EngineStats(
            total_nodes=self.graph.node_count if self.graph else 0,
            active_nodes=self.graph.active_count if self.graph else 0,
            total_edges=len(self.graph._edges) if self.graph else 0,
            pool_size=self.pool.size() if self.pool else 0,
            action_queue_size=len(self.action_queue),
            steps_run=getattr(self, '_steps_run', 0),
            nodes_processed=getattr(self, '_nodes_processed', 0),
            pruned_nodes=self.graph.node_count - self.graph.active_count if self.graph else 0,
            dmn_generated=getattr(self, '_dmn_generated', 0),
            uptime_seconds=time.time() - self._start_time if self._start_time > 0 else 0.0,
            # ── 新增字段 ──
            graph_entropy=graph_entropy,
            total_activations=total_activations,
            growth_strategy=growth_strategy_name,
        )

    def get_action_outputs(self) -> list:
        """Get all nodes that have pending action outputs."""
        return [
            n for n in self.pool.nodes.values()
            if hasattr(n, 'action_output') and n.action_output
        ] if self.pool else []

    def get_graph_summary(self) -> dict:
        """Get a summary of the current graph state."""
        if not self.graph:
            return {"total_nodes": 0, "active_nodes": 0, "total_edges": 0, "node_types": {}}
        types: dict[str, int] = {}
        for node in self.graph._nodes.values():
            types[node.type.value] = types.get(node.type.value, 0) + 1
        return {
            "total_nodes": self.graph.node_count,
            "active_nodes": self.graph.active_count,
            "total_edges": len(self.graph._edges),
            "node_types": types,
        }

    # ═══════════════════════════════════════════════════════════
    # 图导入导出
    # ═══════════════════════════════════════════════════════════

    def export_graph(self, format: str = "dict") -> dict:
        """Export the graph as a dictionary."""
        return self.graph.to_dict()

    def import_graph(self, data: dict):
        """Import a graph from a dictionary, replacing the current graph."""
        self.graph = GoTGraph.from_dict(data)
        # 重建节点池
        self.pool = NodePool()
        for node in self.graph.get_active_nodes():
            self.pool.add(node)
        # 重新绑定 DMN 的图引用
        self._dmn._graph = self.graph
        self._reasoning_loop._graph = self.graph
        self._scheduler._graph = self.graph

    def export_mermaid(self, path: str = "") -> str:
        """Export the graph as a Mermaid diagram.

        Args:
            path: Optional file path to write the Mermaid output.

        Returns:
            The Mermaid diagram string.
        """
        mermaid = self.graph.to_mermaid()
        if path:
            with open(path, "w", encoding="utf-8") as f:
                f.write(mermaid)
        return mermaid

    # ═══════════════════════════════════════════════════════════
    # 健康检查
    # ═══════════════════════════════════════════════════════════

    async def health_check(self) -> bool:
        """Run a health check on all engine components.

        Returns:
            True if all components are healthy, False otherwise.
        """
        try:
            cog_ok = await self._cognition.health_check()
        except Exception:
            cog_ok = False

        graph_ok = self.graph is not None
        pool_ok = self.pool is not None
        scheduler_ok = self._scheduler is not None
        reasoner_ok = self._reasoning_loop is not None
        meta_ok = self._meta is not None
        tools_ok = self._tools is not None
        dmn_ok = self._dmn is not None
        dwt_ok = self._draw_of_thought is not None

        all_ok = all([
            cog_ok, graph_ok, pool_ok, scheduler_ok,
            reasoner_ok, meta_ok, tools_ok, dmn_ok, dwt_ok,
        ])

        if not all_ok:
            failed = []
            if not cog_ok:
                failed.append("cognition")
            if not graph_ok:
                failed.append("graph")
            if not pool_ok:
                failed.append("pool")
            if not scheduler_ok:
                failed.append("scheduler")
            if not reasoner_ok:
                failed.append("reasoning_loop")
            if not meta_ok:
                failed.append("metacognition")
            if not tools_ok:
                failed.append("tools")
            if not dmn_ok:
                failed.append("dmn")
            if not dwt_ok:
                failed.append("draw_of_thought")
            logger.warning("Health check failed", failed=(", ".join(failed)))

        return all_ok
